-- ShamanRestoration.lua
-- Updated May 28, 2025 - Modern Structure
-- Mists of Pandaria module for Shaman: Restoration spec

if UnitClassBase( 'player' ) ~= 'SHAMAN' then return end

local addon, ns = ...
local Hekili = _G[ addon ]
local class, state = Hekili.Class, Hekili.State

local spec = Hekili:NewSpecialization( 264 ) -- Restoration spec ID for MoP

local strformat = string.format
local FindUnitBuffByID, FindUnitDebuffByID = ns.FindUnitBuffByID, ns.FindUnitDebuffByID
local UA_GetPlayerAuraBySpellID = C_UnitAuras.GetPlayerAuraBySpellID

-- Register resources
spec:RegisterResource( Enum.PowerType.Mana )

-- Tier sets
spec:RegisterGear( "tier14", 85304, 85305, 85306, 85307, 85308 ) -- T14 Shaman Set
spec:RegisterGear( "tier15", 95298, 95299, 95300, 95301, 95302 ) -- T15 Shaman Set

-- Talents (MoP 6-tier talent system)
spec:RegisterTalents( {
    -- Tier 1 (Level 15) - Survivability
    nature_guardian            = { 2260, 1, 30884  }, -- Instant heal for 20% health when below 30%
    stone_bulwark_totem        = { 2261, 1, 108270 }, -- Absorb totem that regenerates shield
    astral_shift               = { 2262, 1, 108271 }, -- 40% damage shifted to DoT for 6 sec

    -- Tier 2 (Level 30) - Utility/Control
    frozen_power               = { 2263, 1, 108196 }, -- Frost Shock roots targets for 5 sec
    earthgrab_totem            = { 2264, 1, 51485  }, -- Totem roots nearby enemies
    windwalk_totem             = { 2265, 1, 108273 }, -- Removes movement impairing effects

    -- Tier 3 (Level 45) - Totem Enhancement
    call_of_the_elements       = { 2266, 1, 108285 }, -- Reduces totem cooldowns by 50% for 1 min
    totemic_restoration        = { 2267, 1, 108284 }, -- Destroyed totems get 50% cooldown reduction
    totemic_projection         = { 2268, 1, 108287 }, -- Relocate totems to target location

    -- Tier 4 (Level 60) - Healing Enhancement
    elemental_mastery          = { 2269, 1, 16166  }, -- Instant cast and 30% spell damage buff
    ancestral_swiftness        = { 2270, 1, 16188  }, -- 5% haste passive, instant cast active
    echo_of_the_elements       = { 2271, 1, 108283 }, -- 6% chance to cast spell twice

    -- Tier 5 (Level 75) - Healing/Support
    healing_tide_totem         = { 2272, 1, 108280 }, -- Raid healing totem for 10 sec
    ancestral_guidance         = { 2273, 1, 108281 }, -- Heals lowest health ally for 25% of damage dealt
    conductivity               = { 2274, 1, 108282 }, -- When you cast Healing Rain, you may cast Lightning Bolt, Chain Lightning, Lava Burst, or Elemental Blast on enemies standing in the area to heal all allies in the Healing Rain for 20% of the damage dealt.    conductivity               = { 2274, 1, 108282 }, -- Chain Lightning spread to 2 additional targets
    
    -- Tier 6 (Level 90) - Ultimate
    unleashed_fury             = { 2275, 1, 117012 }, -- Enhances Unleash Elements effects
    primal_elementalist        = { 2276, 1, 117013 }, -- Gain control over elementals, 10% more damage
    elemental_blast            = { 2277, 1, 117014 }  -- High damage + random stat buff
} )

-- Restoration-specific Glyphs
spec:RegisterGlyphs( {
    -- Major Glyphs
    [55456] = "frost_shock",         -- Your Frost Shock no longer slows your enemies, but also no longer shares a cooldown with other shock spells.
    [55440] = "healing_stream_totem", -- Your Healing Stream Totem also reduces damage taken by 10% for allies within its radius.
    [55441] = "healing_wave",        -- Your Healing Wave also heals you for 20% of the amount when you heal someone else.
    [55460] = "healing_stream",      -- Your Healing Stream Totem heals for 30% more, but affects one target at a time.
    [55448] = "riptide",             -- Increases the initial direct healing of your Riptide by 75%, but removes the periodic healing effect.
    [55438] = "spiritwalkers_grace", -- Reduces the cooldown of Spiritwalker's Grace by 60 sec, but reduces the duration by 5 sec.
    [55455] = "flame_shock",         -- Increases the duration of Flame Shock by 6 sec.
    [55449] = "totemic_recall",      -- Your Totemic Recall spell no longer restores mana when recalling totems.
    [55447] = "fire_elemental_totem", -- Increases the duration of your Fire Elemental Totem by 1 min, but increases the cooldown by 2.5 min.
    [55446] = "water_shield",        -- Increases the amount of mana generated by your Water Shield by 50%.
    [55452] = "chaining",            -- Increases the amount healed by Chain Heal by 10% when it jumps to each successive target.
    [55439] = "hex",                 -- Increases the duration of your Hex spell by 20 sec.
    [63273] = "cleansing_waters",    -- When you Cleanse Spirit harmful effects from yourself, you are healed for a small amount.
    
    -- Minor Glyphs
    [58059] = "arctic_wolf",         -- Your Ghost Wolf form appears as an Arctic Wolf.
    [63270] = "astral_recall",       -- Reduces the cooldown on your Astral Recall spell by 2 min.
    [63271] = "astral_fixation",     -- Your Far Sight ability now casts instantly.
    [55454] = "capacitor_totem",     -- Reduces the time before your Capacitor Totem detonates by 2 sec, but increases the cooldown by 15 sec.
    [58057] = "deluge",              -- Increases the range of your Chain Lightning and Chain Heal spells by 5 yards.
    [58058] = "elemental_familiars", -- Your totems no longer have Taunt abilities.
    [58063] = "lava_lash",           -- Your Lava Lash no longer increases damage when your offhand weapon is enchanted with Flametongue, but instead generates one stack of Searing Flame, increasing the damage of your next Searing Totem by 5%, stacking up to 5 times.
    [57720] = "reach_of_the_elements", -- Increases the range of your totems by 5 yards.
    [55461] = "spirit_wolf",         -- Each of your Spirit Wolves attacks add a stack of Spirit Hunt to your target, increasing the healing you receive by 1% for 10 sec and stacking up to 5 times.
    [55437] = "thunderstorm",        -- Your Thunderstorm knocks enemies back a shorter distance.
    [58056] = "totemic_vigor",       -- Increases the health of your totems by 5%.
    [57958] = "water_walking",       -- Your Water Walking spell no longer cancels when recipients take damage.
} )

-- Restoration Shaman specific auras
spec:RegisterAuras( {
    -- Core mechanics
    water_shield = {
        id = 52127,
        duration = 1800,
        max_stack = 3,
        generate = function( t )
            local name, icon, count, debuffType, duration, expirationTime, caster = FindUnitBuffByID( "player", 52127 )
            
            if name then
                t.name = name
                t.count = count
                t.expires = expirationTime
                t.applied = expirationTime - duration
                t.caster = caster
                return
            end
            
            t.count = 0
            t.expires = 0
            t.applied = 0
            t.caster = "nobody"
        end,
    },
    tidal_waves = {
        id = 53390,
        duration = 15,
        max_stack = 2,
        generate = function( t )
            local name, icon, count, debuffType, duration, expirationTime, caster = FindUnitBuffByID( "player", 53390 )
            
            if name then
                t.name = name
                t.count = count
                t.expires = expirationTime
                t.applied = expirationTime - duration
                t.caster = caster
                return
            end
            
            t.count = 0
            t.expires = 0
            t.applied = 0
            t.caster = "nobody"
        end,
    },
    earth_shield = {
        id = 974,
        duration = 600,
        max_stack = 9,
    },
    healing_rain = {
        id = 73920,
        duration = 10,
        max_stack = 1,
    },
    spiritwalkers_grace = {
        id = 79206,
        duration = function() return glyph.spiritwalkers_grace.enabled and 10 or 15 end,
        max_stack = 1,
    },
    
    -- Talents
    ancestral_swiftness = {
        id = 16188,
        duration = 10,
        max_stack = 1,
    },
    elemental_mastery = {
        id = 16166,
        duration = 20,
        max_stack = 1,
    },
    unleash_life = {
        id = 73685,
        duration = 10,
        max_stack = 1,
    },
    
    -- Imbues
    earthliving_weapon = {
        id = 51730,
        duration = 1800,
        max_stack = 1,
    },
    
    -- Totems
    capacitor_totem = {
        id = 118905,
        duration = 5,
        max_stack = 1,
    },
    earthbind_totem = {
        id = 2484,
        duration = 30,
        max_stack = 1,
    },
    earthgrab_totem = {
        id = 51485,
        duration = 20,
        max_stack = 1,
    },
    fire_elemental_totem = {
        id = 2894,
        duration = function() return glyph.fire_elemental_totem.enabled and 120 or 60 end,
        max_stack = 1,
    },
    grounding_totem = {
        id = 8177,
        duration = 15,
        max_stack = 1,
    },
    healing_stream_totem = {
        id = 5394,
        duration = 15,
        max_stack = 1,
    },
    healing_tide_totem = {
        id = 108280,
        duration = 10,
        max_stack = 1,
    },
    mana_tide_totem = {
        id = 16190,
        duration = 12,
        max_stack = 1,
    },
    spirit_link_totem = {
        id = 98008,
        duration = 6,
        max_stack = 1,
    },
    stone_bulwark_totem = {
        id = 108270,
        duration = 30,
        max_stack = 1,
    },
    stoneclaw_totem = {
        id = 5730,
        duration = 15,
        max_stack = 1,
    },
    stoneskin_totem = {
        id = 8071,
        duration = 15,
        max_stack = 1,
    },
    stormlash_totem = {
        id = 120668,
        duration = 10,
        max_stack = 1,
    },
    tremor_totem = {
        id = 8143,
        duration = 10,
        max_stack = 1,
    },
    windwalk_totem = {
        id = 108273,
        duration = 6,
        max_stack = 1,
    },
    
    -- Healing effects
    riptide = {
        id = 61295,
        duration = 18,
        tick_time = 3,
        max_stack = 1,
    },
    healing_stream = {
        id = 5672,
        duration = 15,
        max_stack = 1,
    },
    earthliving = {
        id = 51945,
        duration = 12,
        tick_time = 3,
        max_stack = 1,
    },
    
    -- Debuffs
    flame_shock = {
        id = 8050,
        duration = function() return glyph.flame_shock.enabled and 27 or 21 end,
        tick_time = 3,
        max_stack = 1,
    },
    frost_shock = {
        id = 8056,
        duration = 8,
        max_stack = 1,
    },
    frozen = {
        id = 94794,
        duration = 5,
        max_stack = 1,
    },
    earthgrab = {
        id = 64695,
        duration = 5,
        max_stack = 1,
    },
    
    -- Defensives
    astral_shift = {
        id = 108271,
        duration = 6,
        max_stack = 1,
    },
    stone_bulwark_absorb = {
        id = 114893,
        duration = 30,
        max_stack = 1,
    },
    
    -- Utility
    ghost_wolf = {
        id = 2645,
        duration = 3600,
        max_stack = 1,
    },
    water_walking = {
        id = 546,
        duration = 600,
        max_stack = 1,
    },
    water_breathing = {
        id = 131,
        duration = 600,
        max_stack = 1,
    },
    
    -- MoP-specific talents
    ancestral_guidance = {
        id = 108281,
        duration = 10,
        max_stack = 1,
    },
    conductivity = {
        id = 108282,
        duration = 10,
        max_stack = 1,
    },
} )

-- Restoration Shaman abilities
spec:RegisterAbilities( {
    -- Core healing abilities
    healing_wave = {
        id = 77472,
        cast = function() return buff.tidal_waves.up and 1.5 * 0.7 * haste or 1.5 * haste end,
        cooldown = 0,
        gcd = "spell",
        
        spend = 0.10,
        spendType = "mana",
        
        startsCombat = false,
        texture = 136043,
        
        handler = function()
            if buff.tidal_waves.up then
                removeStack("tidal_waves")
            end
            -- Earthliving proc
            if buff.earthliving_weapon.up and math.random() < 0.20 then -- 20% proc chance
                applyDebuff("target", "earthliving")
            end
        end,
    },
    
    greater_healing_wave = {
        id = 77472,
        cast = function() return buff.tidal_waves.up and 3 * 0.7 * haste or 3 * haste end,
        cooldown = 0,
        gcd = "spell",
        
        spend = 0.18,
        spendType = "mana",
        
        startsCombat = false,
        texture = 136043,
        
        handler = function()
            if buff.tidal_waves.up then
                removeStack("tidal_waves")
            end
            -- Earthliving proc
            if buff.earthliving_weapon.up and math.random() < 0.20 then -- 20% proc chance
                applyDebuff("target", "earthliving")
            end
        end,
    },
    
    healing_surge = {
        id = 8004,
        cast = function() return buff.tidal_waves.up and 1.5 * 0.7 * haste or 1.5 * haste end,
        cooldown = 0,
        gcd = "spell",
        
        spend = 0.22,
        spendType = "mana",
        
        startsCombat = false,
        texture = 136044,
        
        handler = function()
            if buff.tidal_waves.up then
                removeStack("tidal_waves")
            end
            -- Earthliving proc
            if buff.earthliving_weapon.up and math.random() < 0.20 then -- 20% proc chance
                applyDebuff("target", "earthliving")
            end
        end,
    },
    
    chain_heal = {
        id = 1064,
        cast = function() return 2.5 * haste end,
        cooldown = 0,
        gcd = "spell",
        
        spend = 0.20,
        spendType = "mana",
        
        startsCombat = false,
        texture = 136042,
        
        handler = function()
            -- Earthliving proc
            if buff.earthliving_weapon.up and math.random() < 0.20 then -- 20% proc chance
                applyDebuff("target", "earthliving")
            end
            addStack("tidal_waves", nil, 2)
        end,
    },
    
    riptide = {
        id = 61295,
        cast = 0,
        cooldown = 6,
        gcd = "spell",
        
        spend = 0.08,
        spendType = "mana",
        
        startsCombat = false,
        texture = 252995,
        
        handler = function()
            if not glyph.riptide.enabled then
                applyBuff("target", "riptide")
            end
            -- Earthliving proc
            if buff.earthliving_weapon.up and math.random() < 0.20 then -- 20% proc chance
                applyDebuff("target", "earthliving")
            end
            addStack("tidal_waves", nil, 2)
        end,
    },
    
    earth_shield = {
        id = 974,
        cast = 0,
        cooldown = 0,
        gcd = "spell",
        
        spend = 0.10,
        spendType = "mana",
        
        startsCombat = false,
        texture = 136089,
        
        handler = function()
            applyBuff("target", "earth_shield")
            buff.earth_shield.stack = 9
        end,
    },
    
    healing_rain = {
        id = 73920,
        cast = function() return 2 * haste end,
        cooldown = 10,
        gcd = "spell",
        
        spend = 0.38,
        spendType = "mana",
        
        startsCombat = false,
        texture = 136037,
        
        handler = function()
            applyBuff("healing_rain")
        end,
    },
    
    -- Totems
    healing_stream_totem = {
        id = 5394,
        cast = 0,
        cooldown = 30,
        gcd = "totem",
        
        spend = 0.04,
        spendType = "mana",
        
        startsCombat = false,
        texture = 135127,
        
        handler = function()
            applyBuff("healing_stream_totem")
        end,
    },
    
    healing_tide_totem = {
        id = 108280,
        cast = 0,
        cooldown = 180,
        gcd = "totem",
        
        toggle = "cooldowns",
        
        spend = 0.18,
        spendType = "mana",
        
        startsCombat = false,
        texture = 538569,
        
        handler = function()
            applyBuff("healing_tide_totem")
        end,
    },
    
    mana_tide_totem = {
        id = 16190,
        cast = 0,
        cooldown = 180,
        gcd = "totem",
        
        toggle = "cooldowns",
        
        spend = 0.07,
        spendType = "mana",
        
        startsCombat = false,
        texture = 4710368,
        
        handler = function()
            applyBuff("mana_tide_totem")
        end,
    },
    
    spirit_link_totem = {
        id = 98008,
        cast = 0,
        cooldown = 180,
        gcd = "totem",
        
        toggle = "cooldowns",
        
        spend = 0.12,
        spendType = "mana",
        
        startsCombat = false,
        texture = 237586,
        
        handler = function()
            applyBuff("spirit_link_totem")
        end,
    },
    
    capacitor_totem = {
        id = 108269,
        cast = 0,
        cooldown = function() return glyph.capacitor_totem.enabled and 60 or 45 end,
        gcd = "totem",
        
        spend = 0.05,
        spendType = "mana",
        
        startsCombat = false,
        texture = 136013,
        
        handler = function()
            applyBuff("capacitor_totem")
        end,
    },
    
    earthbind_totem = {
        id = 2484,
        cast = 0,
        cooldown = 30,
        gcd = "totem",
        
        spend = 0.05,
        spendType = "mana",
        
        startsCombat = false,
        texture = 136102,
        
        handler = function()
            applyBuff("earthbind_totem")
        end,
    },
    
    tremor_totem = {
        id = 8143,
        cast = 0,
        cooldown = 60,
        gcd = "totem",
        
        spend = 0.05,
        spendType = "mana",
        
        startsCombat = false,
        texture = 136108,
        
        handler = function()
            applyBuff("tremor_totem")
        end,
    },
    
    -- Utility and defensives
    water_shield = {
        id = 52127,
        cast = 0,
        cooldown = 0,
        gcd = "spell",
        
        spend = 0.1,
        spendType = "mana",
        
        startsCombat = false,
        texture = 132315,
        
        handler = function()
            applyBuff("water_shield")
            buff.water_shield.stack = 3
        end,
    },
    
    earthliving_weapon = {
        id = 51730,
        cast = 0,
        cooldown = 0,
        gcd = "spell",
        
        spend = 0.1,
        spendType = "mana",
        
        startsCombat = false,
        texture = 237575,
        
        handler = function()
            applyBuff("earthliving_weapon")
        end,
    },
    
    purify_spirit = {
        id = 77130,
        cast = 0,
        cooldown = 8,
        gcd = "spell",
        
        spend = 0.06,
        spendType = "mana",
        
        startsCombat = false,
        texture = 451166,
        
        handler = function()
            -- Cleanse effects
            if glyph.cleansing_waters.enabled then
                -- Apply self heal from glyph
            end
        end,
    },
    
    spiritwalkers_grace = {
        id = 79206,
        cast = 0,
        cooldown = function() return glyph.spiritwalkers_grace.enabled and 60 or 120 end,
        gcd = "spell",
        
        toggle = "cooldowns",
        
        startsCombat = false,
        texture = 451170,
        
        handler = function()
            applyBuff("spiritwalkers_grace")
        end,
    },
    
    ghost_wolf = {
        id = 2645,
        cast = 0,
        cooldown = 0,
        gcd = "spell",
        
        startsCombat = false,
        texture = 136095,
        
        handler = function()
            applyBuff("ghost_wolf")
        end,
    },
    
    astral_shift = {
        id = 108271,
        cast = 0,
        cooldown = 90,
        gcd = "off",
        
        toggle = "defensives",
        
        startsCombat = false,
        texture = 538565,
        
        handler = function()
            applyBuff("astral_shift")
        end,
    },
    
    stone_bulwark_totem = {
        id = 108270,
        cast = 0,
        cooldown = 60,
        gcd = "totem",
        
        toggle = "defensives",
        
        spend = 0.05,
        spendType = "mana",
        
        startsCombat = false,
        texture = 135861,
        
        handler = function()
            applyBuff("stone_bulwark_totem")
            applyBuff("stone_bulwark_absorb")
        end,
    },
    
    -- Talents
    elemental_mastery = {
        id = 16166,
        cast = 0,
        cooldown = 120,
        gcd = "off",
        
        toggle = "cooldowns",
        
        startsCombat = false,
        texture = 136115,
        
        handler = function()
            applyBuff("elemental_mastery")
        end,
    },
    
    ancestral_swiftness = {
        id = 16188,
        cast = 0,
        cooldown = 60,
        gcd = "off",
        
        toggle = "cooldowns",
        
        startsCombat = false,
        texture = 136076,
        
        handler = function()
            applyBuff("ancestral_swiftness")
        end,
    },
    
    ancestral_guidance = {
        id = 108281,
        cast = 0,
        cooldown = 120,
        gcd = "off",
        
        toggle = "cooldowns",
        
        startsCombat = false,
        texture = 538564,
        
        handler = function()
            applyBuff("ancestral_guidance")
        end,
    },
    
    unleash_elements = {
        id = 73680,
        cast = 0,
        cooldown = 15,
        gcd = "spell",
        
        spend = 0.04,
        spendType = "mana",
        
        startsCombat = false,
        texture = 462650,
        
        handler = function()
            applyBuff("unleash_life")
        end,
    },
} )

-- State Expressions for Restoration
spec:RegisterStateExpr( "tidal_stacks", function()
    return buff.tidal_waves.stack
end )

-- Range
spec:RegisterRanges( "healing_wave", "flame_shock", "earth_shock", "frost_shock", "wind_shear" )

-- Options
spec:RegisterOptions( {
    enabled = true,
    
    aoe = 3,
    
    gcd = 1645,
    
    nameplates = true,
    nameplateRange = 8,
    
    damage = true,
    damageExpiration = 8,
    
    potion = "jade_serpent",
    
    package = "Restoration",
} )

-- Default pack for MoP Restoration Shaman
spec:RegisterPack( "Restoration", 20250515, [[Hekili:T1vBVTTnu4FlXiPaQWKrdpvIbKmEbvJRLwwxP2rI1mzQiQ1GIugwwtyQsyBvHnYJP6LP56NHJUHX2Z)OnRXYQZl6R)UNB6QL(zhdkr9bQlG(tB8L4Wdpb3NNVh(GWdFOdpNFpdO8Hdm6Tw(acm2nDWZ5MjsXyJKCtj3cU5sIVOd8jkzPsMLIX65MuLY1jrwLkKWrZA3CluOKCvId8LHIyyIeLSr1WIJ1jPr7cYeKwrJIuWXRKtFDlYkLmCPFJr(4OsZQR]] )

-- Register pack selector for Restoration
spec:RegisterPackSelector( "restoration", "Restoration", "|T136052:0|t Restoration",
    "Handles all aspects of Restoration Shaman healing with focus on totems and Chain Heal usage.",
    nil )
